version: "3.9"
services:
  api:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./rules:/app/rules
      - ./app/templates:/app/app/templates
    ports:
      - "8000:8000"
    depends_on:
      - mailhog
      - n8n
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - GENERIC_TIMEZONE=America/Buenos_Aires
    volumes:
      - n8n_data:/home/node/.n8n
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
volumes:
  n8n_data:
